name: license_server_rest
description: "Rest models returned by the license server"
version: 0.0.1
publish_to: none
repository: https://github.com/necodeIT/license_server_rest

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  bloc: ^8.1.4
  collection: ^1.18.0
  either_dart: ^1.0.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  mcquenji_core:
    git:
      url: https://github.com/mcquenji/mcquenji_core.git
  modular_core: ^3.3.3

dev_dependencies:
  architecture_linter: ^0.2.2
  build_runner: ^2.4.11
  flutterando_analysis: ^0.0.2
  freezed: ^2.5.2
  json_serializable: ^6.8.0

dependency_overrides:
  modular_core:
    git:
      url: git@github.com:necodeIT/modular.git
      path: modular_core
