name: license_server_rest
description: "Rest models returned by the license server"
version: 0.0.1
publish_to: none
repository: https://github.com/necodeIT/license_server_rest

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  dotenv: ^4.2.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.11
  flutterando_analysis: ^0.0.2
  freezed: ^2.5.2
  json_serializable: ^6.8.0
